# Database configuration
database:
  host: postgres
  port: 5432
  sslmode: disable
  max_conns: 10
  min_conns: 2

# Migrations configuration
migrations:
  path: ./migrations
  auto: true

# Application configuration
app:
  log_level: info
  cache_dir: /app/cache
  timezone: Europe/Moscow

# Test configuration (опционально)
test:
  db_host: localhost
  migrations_path: ./migrations
  handler_migrations_path: ./migrations